version: "3.8"

services:
  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - prometheus_data:/prometheus
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  alert-manager:
    image: prom/alertmanager
    restart: always
    ports:
      - "9093:9093"

  grafana:
    image: grafana/grafana:7.2.0
    restart: always
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_PATHS_LOGS=/var/log/grafana
      - GF_PATHS_PLUGINS=/var/lib/grafana/plugins
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - grafana_data:/var/lib/grafana

volumes:
  prometheus_data:
  grafana_data:
