global:
  scrape_interval: 10s

rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: expenses-api
    static_configs:
      - targets:
        - host.docker.internal:8080

  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets:
        - localhost:9090
